language: python

cache:
    directories:
        - $HOME/.cache/pip

# container-based infrastructure
sudo: false

matrix:
  include:
    - python: 2.7
    - python: 3.6

install:
 - 'python setup.py install'
 - '(python3 --version 2>/dev/null && sh install-py3-scapy.sh) || true'

script: 
 - './test.sh'
